### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#118]
We might need an Options menu where you can change message speed and whatnot. This would also be useful when/if we add a mode where it informs you what things are. Could also put a keymapping option here. Or maybe that would go in an .ini file because the originals never really had anything like that. But we could make it look really authentic!

**Comment by psywombats** [comment]
Toggling "noob mode" should be one of these options.

**Comment by psywombats** [comment]
Noob mode is now automatic and isn't that offensive. Will still need to get to this eventually though.

**Comment by psywombats** [comment]
Deprecated.
