### ISSUE TITLE
Plan out the hub world

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#137]
Need to figure out what the hub world is actually going to be like. Some ideas I remember from nowhere in particular:
* X-Plane, whatever that means
* Makai aka Demon World, whatever that means
* giant ocean that the player traverses via turtle (??)
* a giant hole aka The Abyss
* a huge ruined castle thing with gates at the four cardinal directions

Needs more brainstorming.

**Comment by crumley467** [comment]
Based on our conversation, I'm going to add "scaffolding left behind by the creator while he was building the world." Benefit of this is we could have a wierd little subworld where the creator is hanging out and hes like "wtf how did you get here." His name can even be psy_wombats ;)
