### ISSUE TITLE
Cannot reselect attack

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#140]
When you're in combat and you pick LONG and go to pick a group to attack with LONG, you can't hit escape to select BRONZE instead until you select a group and then advance to the next character and THEN hit escape to go back to the previous character. As far as I know this has always been a bug but hadn't bothered me enough to report it until now.

**Comment by psywombats** [comment]
You're hitting the START button instead of the B button. I've made it so both work now.

**Comment by crumley467** [comment]
Thanks!
