### ISSUE TITLE
New inventory icons

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#141]
I think we need more armor pieces ala FFL3, so that humans can make use of their extra item slots. FFL3 had a jewelry/bangal/other item slot that I think could work for our purposes. So I might pick up a $XTALISMAN that protects from fire or something. Also do we have a shoe icon yet?

New icons:
 - [x] Knife
 - [x] Pendant
 - [x] Mystic sword
 - [x] Cannon

**Comment by psywombats** [comment]
Could also use a knife icon -- FFL3 had these and it'd help the P-KNIFE be a little more obvious

**Comment by crumley467** [comment]
Yep we have a boot I believe. Adding a pendant thingie should be no trouble

**Comment by psywombats** [comment]
Oh, could also use a spear maybe? Although I only remember the WHITE and ODIN spears.

**Comment by psywombats** [comment]
Updated with full list of stuff we'll need. Also added a mystic sword that'll be relevant for world 4 probably. FFL3 had a slightly different sword icon for MASAMUNE, XCALIBER, etc that was a little different than the normal sword icon so you could tell it was ~super cool~

**Comment by crumley467** [comment]
Gonna upload in a minute. Tell me what you think.

**Comment by psywombats** [comment]
Looking good.

**Comment by psywombats** [comment]
Would be neat to have an artillery icon similar to FFL2/3 for things like TANK, ROCKET, MISSILE etc
