### ISSUE TITLE
New tiles for world 2

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#142]
For the worm's castle, looking for a wider entryway chip, similar to: http://fantasyanime.com/saga/images/ffl3map08-Present-TowerOfChaos.png marked E

It also might be nice to have a narrow version for the overhead room transition, but maybe the existing open door can accomplish that.

Multiple types of door would also be neat (both 1-tall and 2-tall). The wooden door looks a little out of place in some areas (Babel, world 2 castles)

- [x] - Small castle door
- [x] - Large castle door
- [x] - Statue or similar (use the squares where the new rock square thing is)
- [x] - Doublewide door or entryway
- [x] - Tileable staircase
- [x] - Switch or lever
- [x] - Bookcase

**Comment by psywombats** [comment]
Also would appreciate a pull lever (or some other switch) and a multi-tile wide staircase.

**Comment by psywombats** [comment]
If you're feeling ambitious, a statue would also be much appreciated. Or some other beefy 1*2 decoration. Pillars and banners can only go so far.

**Comment by crumley467** [comment]
Yeah i can manage those

**Comment by psywombats** [comment]
Updated with a list of outstanding stuff

**Comment by crumley467** [comment]
dude thats fucking sweet

**Comment by psywombats** [comment]
Could also use a bookcase

**Comment by crumley467** [comment]
Uploaded that statue long ago.
