### ISSUE TITLE
Rebalance the beast and sword and other slayer weapons

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#144]
We need to come up with a concrete breakdown of what "slayer classes" we have. FFL had undead, aquatic, draconic, and goblin. I think we can get this system a little cleaner by using monster families rather than these explicit flags. The current classes we have (animal, aquatic, draconic) are pretty nonsensical beast animal is OP, there's only one aquatic family, and no dragons.

Some ideas for slayer groups (@crumley467 feel free to add more):
 * Vermin (rats, weasels)
 * Beasts (rats, weasels, cats, dogs)
 * Undead (skeletons, zombies, ghosts)
 * Birds (birds, magic birds)
 * Unlife (statues)
 * Insects (flies, armored insects)
 * Slimes (slimes, diseases)

They probably need slayer names attached that most likely won't be authentic. I guess $ABUGBITER and $ABIRDBANE are okay, but generally FFL follows $AOGRE slays goblins, $ADRAGON slays dragons, etc, so we'd more want things like $ABEAST... except something like $ASLIME or $AVERMIN doesn't exactly sound great. Thoughts before I implement?

**Comment by psywombats** [comment]
Changed to a $AWHITE for a lower-level undead slayer and kept the $ACORAL, that is less expensive but only slays annoying jellyfish.

**Comment by crumley467** [comment]
Herp I wish I'd been on the ball enough to read this issue. I think those are all perfectly reasonable slayer weapons except why do we need two rat slaying weapons? And these will only work if the tooltip tells you what they slay. Or maybe not. Whichever.

**Comment by psywombats** [comment]
They're not all in-game, just WHITE and CORAL.
