### ISSUE TITLE
Moving in a direction after leaving a cave causes bugs

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#147]
I only noticed this while exiting the cave system in the second world, but if, right after teleporting out of a cave, you mash any direction quickly, you teleport back into the cave. No idea what causes it. Try exiting a cave with access in the east/west direction and pressing and holding right/left as the screen transition is going.

**Comment by psywombats** [comment]
Issue happens when holding two directions when one direction is inaccessible.

**Comment by psywombats** [comment]
Turns out a certain collision trigger has been wrong for a very long time.
