### ISSUE TITLE
New chips for world 3

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#149]
Stuff we'll definitely need:

 - [x] Walkway
 - [x] Future dungeon wall
 - [x] Future building exterior
 - [x] Future door
 - [x] Future small door
 - [x] Future window
 - [x] Future exterior wall
 - [x] Scaffolding for raised walkways
 - [x] City wall
 - [x] Futuristic city world map chip (x2, one for city of angels, one for misc power plants)

Stuff it'd be good to have:

 - [x] "Machine"-y chip (or chips?) for a giant machine or cannon
 - [ ] Monorail car exterior
 - [x] Monorail track (world map scale)
 - [x] Crater

Stuff it'd be cool to have:

 - [x] Modern countertop

**Comment by psywombats** [comment]
Added some more junk based on story ideas.

**Comment by psywombats** [comment]
Can you make sure the upper chip items are actually in the chipset? Couldn't find that neat skyscraper thing

**Comment by psywombats** [comment]
@crumley467 Other notes... That metallic top chip (on the right, id 125) doesn't tile well at all, ends up with no lines on the left and a double horizontal line. The wall chip is also unusable because the white side bleeds into the ground; needs siding chips

**Comment by psywombats** [comment]
The window chip is a little large to use in this scale

**Comment by psywombats** [comment]
Whoops, just saw the upper chips that were added.

**Comment by crumley467** [comment]
I can't tell which one you're talking about. I tried tiling what I thought you were talking about (http://i.imgur.com/5SNmtYO.png) which I thought looked fine. Then I thought you might be talking about this chip (http://i.imgur.com/x6Mxwqm.png) which, yes, does not tile well vertically. I was supposed to be a board to go over the scaffolding. For whatever reason I can't see the tile IDs so I just counted to that first one I mentioned. Furthermore, there is a glass tile chip in the verrry first row of the chipset which could get some use in this world. Also, if you could elaborate on what you mean by window chip, that'd be great. There are a bunch of chips that sort of look like windows.

**Comment by crumley467** [comment]
And this just aleviates some concerns I have about the chip being used for building exteriors or something. I feel like we need a chip that looks like the texture of the skyscraper being used in the overworld. This is that chip maybe.  http://i.imgur.com/gt4u0CS.png

**Comment by psywombats** [comment]
I was talking about that first chip, yeah. I should mention I went through last night and made a couple edits to get that chip tiling right. That second chip I'm using as a monorail track, it looks pretty good. I shrunk some windows and got them to scale already.

**Comment by crumley467** [comment]
Swag. I'm happy then. Although I could definately make that chip actually look like a monorail's rail

**Comment by psywombats** [comment]
Are you going to be working any more on this? I've got a placeholder machine and stuff that should work for the other chips.

**Comment by crumley467** [comment]
I was gonna get some work on it done tonight. Are your placeholders ok-looking or are they just chips that say "place" and "holder" respectively?

**Comment by psywombats** [comment]
The machine is a bunch of piping and magic crystals, is what I meant. It might look better with a designated chip for it but it doesn't matter too much. That statue from world2 might be higher priority I think. A monorail would also be helpful even if we probably shouldn't display the interior.

**Comment by crumley467** [comment]
You still want that monorail?

**Comment by psywombats** [comment]
I think we'll live without it.
