### ISSUE TITLE
Magic Stone wierdness

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#154]
If you look at your save file, it shows all of the stones you have. But instead of "earth=2" it says "earth=1" twice. The little box showing how many you have in game only shows an entry once, but I know I've collected at least two of all the kinds, and in game it shows as one each. Furthermore, after collecting a second stone of the last time,  the display box extended off the bottom of the screen.

**Comment by crumley467** [comment]
"collectables" : {
			"quantities" : {
				"stone_air" : 1,
				"stone_earth" : 1,
				"stone_black" : 1,
				"stone_white" : 1,
				"stone_white" : 1,
				"stone_earth" : 1,
				"stone_black" : 1,
				"stone_fire" : 1,
				"stone_black" : 1
			}

**Comment by psywombats** [comment]
Issue with key comparison.
