### ISSUE TITLE
Last character ability increment is wonky

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#180]
As you use the last character's ability, you can actually see it increment down by one before the battle round actually starts.
Its really fast so you wouldnt see it unless you were looking for it.

**Comment by crumley467** [comment]
I had another thought about this. This still happens in cases where the ability does not actually get used due to victory or attack on now-dead monster. This could potentially lead to ability being incremented down when they are not actually used. Will investigate further!

**Comment by psywombats** [comment]
That's... very odd, now that you mention it. I'm very confident that the deduction isn't actually happening, because I've run tests with (for instance) 4 humans each with 50-use swords vs 200 monsters and had all the battles complete successfully.

**Comment by crumley467** [comment]
So what you're saying is that it either a) goes back up later or b) the result of the round of combat is known as soon as you finish selecting and this *doesn't* actually happen if the attack isn't actually going to be delivered and I'm just imagining things

**Comment by psywombats** [comment]
actually that's probably what's happening, combat is all simulated immediately once the turns are entered
