### ISSUE TITLE
Drop rate for ROCKET from BOMBARDIER is too high

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#186]
Got an inventory fulla rockets

**Comment by psywombats** [comment]
Weird. It's the same droprate for all enemies. Maybe there are just way too many bombadiers?

**Comment by crumley467** [comment]
Maybe when there are large stacks of them yeah
Felt like almsot every other encounter dropped one

**Comment by psywombats** [comment]
I adjusted their individual drop rate to be half of the standard. I think they're the only common item-dropper that shows up in hoards or something.
