### ISSUE TITLE
Possible framerate drop in Underground City

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#188]
This might not actually be true? But nothing changed elsewhere on my computer. Maybe just try to replicate it on your machine

**Comment by crumley467** [comment]
This may, if true, affect all of world 4

**Comment by psywombats** [comment]
Looks like there's steady performance degradation. Possibly after lots of maps or maybe after lots of battles. Will have to investigate.

**Comment by psywombats** [comment]
Still no idea what's causing this. Tried running 300 battles, 300 cutscenes, 1000 dialog boxes, 100 teleports... ugh
