### ISSUE TITLE
Should useful side-worlds have their own names rather than their floor numbers?

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#237]
Hard yes for me, but i assume there is a reason this is not the case. I am thinking of the Zoological Society, the Bazaar, the Lost Magic Petagram Cave, etc. One would assume that we'd need to name all of the side worlds, and some do not lend themselves to this easily.

**Comment by psywombats** [comment]
They have names in teleports. Should probably put them on the actual floor display as well

**Comment by psywombats** [comment]
It's been decided they will going forward

**Comment by psywombats** [comment]
Should all be filled out now
