### ISSUE TITLE
World 1 BGM

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#275]
SGarbage will cover this. Close the issue when he's done.

**Comment by SkankinGarbage** [comment]
Changed name of issue to "World 1 BGM".

Status: 1 piece still needs writing, 1 piece needs rewritten, all but two pieces need a "second pass", where I look at volume balance, note durations, and other nitpicky stuff. 

Currently, working on the second pass. The final two pieces aren't necessary for the demo, and I won't be prioritizing writing them. This issue will be closed when I finish the second pass on all pieces.

**Comment by SkankinGarbage** [comment]
Meant to close this quite a while ago. Second pass is done. Stuff that technically still needs to be done:

- Track 9 - Plainstown destroyed event - needs to be rewritten (The current track will do if I don't rewrite it before the demo)
- Track 10 - Hero Castle - needs to be written (Town theme will do if I don't write it before the demo)
- Very brief "third pass" on like two or three pieces.

These issues, however, are extremely minor, and my efforts are better spent on preparing the sound effects at the moment. When we're getting close to demo time, I will take a look into these last issues. For now, though, it's in a state that I'm happy with.
