### ISSUE TITLE
Implement OGG looping

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#281]
https://andrewmushel.com/articles/looping-music-in-unity/

**Comment by psywombats** [comment]
@SkankinGarbage think this should be moved up to the demo release?

**Comment by SkankinGarbage** [comment]
Well, it's hardly ruining the experience, so I'd agree that it's not critical. I also recently found a more accurate way to find loop points, so I was gonna redo them anyways. Especially if it's a lot of work, let's not worry about it for now. When the time comes, let me know if there's any information I can give you that would help.
