### ISSUE TITLE
Reduce SFX filesize

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#286]
They range from 200kb-1mb. Ideally they should all be under 100kb. Can reduce quality of the .wavs and reduce from stereo to mono.

**Comment by psywombats** [comment]
They get compressed by Unity a bit. Still should be mono.

**Comment by SkankinGarbage** [comment]
I could also convert all of them to OGG files unless there's any reason you think I shouldn't.

**Comment by psywombats** [comment]
@SkankinGarbage That'd be really helpful actually -- and the majority can probably be mono as well

**Comment by SkankinGarbage** [comment]
Meant to close this forever ago. All SFX files were converted to OGG files.
