### ISSUE TITLE
Whips crash the game

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#337]
COIL THE WHIP

**Comment by psywombats** [comment]
Can't repro this. Appears to be working?

**Comment by SkankinGarbage** [comment]
I keep meaning to check this, and then I keep not-checking it. Will make a point to do so very soon.

**Comment by psywombats** [comment]
Definitely still happens, just repro'd it for the first time

**Comment by psywombats** [comment]
Was some questionable logic that basically caused the whip to cancel the target's action, sure... by poofing the whip user out of existence
