### ISSUE TITLE
World 2 - There's no contingency in place for reaching the Western Port via the caves

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#343]
Basically, if you first reach the west via the caves, the cutscene doesn't play if you enter the port. Also, if you exit and re-enter, Lara and the Worm Soldiers are still there, but the dead Wolf Soldiers are gone. Not sure how this affects the cutscene if you cause this to happen and then go back to the Eastern Port to trigger the cutscene normally.

I've kept a save at this spot to do further research if necessary.

**Comment by psywombats** [comment]
Hmm, I guess this is best solved by just fixing the western port so that it's possible to sail east without running into Lara, and gating the rest of the game on actually sailing east -> west to trigger that scene
