### ISSUE TITLE
World 2 - Starting the cutscene at the end of Wolf Castle is a little weird

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#346]
You can't walk onto the space in front of the bars, but you can trigger the cutscene by walking up to that impassable space and pressing a button.

**Comment by psywombats** [comment]
will have to confirm this is fixed when that cutscene's done

**Comment by SkankinGarbage** [comment]
Yeah, there's no issue anymore, should have probably assumed it was due to the cutscene being incomplete anyways.
