### ISSUE TITLE
Monster Morphs - The explanation for morphing into an old monster is off

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#349]
The text explains that, since you've morphed into Monster X (let's use NEPHIL as an example) already, you can morph into any other monster of the same tier. Cool.

The text goes on to explain that, if you morph into NEPHIL anyways, you get a stronger version. This doesn't seem to be true unless your current form is already NEPHIL. If I'm some other monster morphing eating meat that would normally turn me into a NEPHIL, and I use the Same-Morphing menu to turn into a NEPHIL anyways, it just has the same stats as a normal NEPHIL.

**Comment by psywombats** [comment]
although weirdly it looks like the code just boosted stats by 20% whenever you used the menu, which seems really weird...
