### ISSUE TITLE
Two Robo-glitches dealing with equipment

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#350]
1. If you remove equipment that lowers a Robot's max HP, their current HP remains above their max.

2. This difference is applied to Inn fees as an effective "discount". In other words, if some people are missing HP, but your Robot has 70/50 HP, the Inn fee is lowered by 20 (Or possibly just lowered to 0? I couldn't actually test this). Staying at an Inn puts the 70/50 robot back to 50/50.

I have screenshots if you need, but you can reproduce this really easy at the beginning of the game with a 4-Robot party; just unequip all of the leader's Bronze Gauntlets, give them to other people, then unequip them again.

**Comment by psywombats** [comment]
Was an issue in the same-tier swap code
