### ISSUE TITLE
World 1 Redux: You can supersede the dialogue with the ELDER by getting the ROM first

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#384]
This is not a likely scenario to come up, but if you run right past the Home Town and get the ROM, if you go back to town, your first conversation with the Elder will lead to the cutscene of him fixing BORG instead of the one where he explains what happened to BORG.

**Comment by psywombats** [comment]
Seems unlikely enough that I'd rather not write anything for it
