### ISSUE TITLE
Info Panel - Second pass

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#406]
O-Poison states that it grants Petrification immunity.

Toxic Skin has no entry for "On Trigger".

The "Cure" item is missing a line break after "Affects: Ally".

Stench: Under the "Debuff increased by:" column, it says it's decreased by "userMana" (i.e there's no space between the words).

**Comment by psywombats** [comment]
O-Poison: it actually did grant o-stone, whoops
Toxic skin: filled out descriptions for riders on status + attack
Cure: added linebreaks for healing items
Stench: added the space for debuffs
