### ISSUE TITLE
NRE when choosing to end game after losing

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#442]
Might be related to ending the game during battles with cutscenes before/after? This happened on Moloch.

**Comment by psywombats** [comment]
need a stack trace to diagnose this

**Comment by psywombats** [comment]
Threw in some code to make this less likely (around resets) but yeah, will need a stack trace to do anything concrete about this

**Comment by psywombats** [comment]
I think this should be solved now. I hope.
