### ISSUE TITLE
Softlock when trying to close a shop menu

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#446]
InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
GenericSelector+<>c__DisplayClass15_0.<SelectItemAsync>b__0 (InputManager+Command command, InputManager+Event ev) (at Assets/Scripts/UI/ListSelector/GenericSelector.cs:77)
AnonymousListener.OnCommand (InputManager+Command command, InputManager+Event eventType) (at Assets/Scripts/IO/AnonymousListener.cs:17)
InputManager.Update () (at Assets/Scripts/IO/InputManager.cs:86)

**Comment by psywombats** [comment]
added some safeguards here, might not fully cover it but otherwise need some repro steps
