### ISSUE TITLE
Using BLOOM to try and fix someone's weapons/abilities is buggy

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#455]
- Cancelling out of someone's ability menu doesn't switch back to the inventory menu, but the cursor is clearly moving around on the inventory menu

- If you cause the above glitch to happen, and select a second equipment menu, you can't continue the game, because attempting to leave the menu screen takes you back to one of the equipment menus.

This is probably true with ARCANE if it uses the same interface, but I've never tried it.

**Comment by psywombats** [comment]
Yeah ARCANE used to be battle-only. I've implemented the in-battle interface for these items now.
