### ISSUE TITLE
Maelstrom caused a softlock in combat

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#472]
One of the enemy groups (RAIJU x1) just disappeared. Maelstrom killed all the enemies in the remaining group, after which the game locked.

-------

Happened a second time. Behemoth x2, Sphinx x2. Set two of my party members on each group (all party members used SAW for reference). The members in the Behemoth group did nothing, and when the Sphinxes were killed at the end of the turn, the victory music played and the game softlocked again. The main difference here is that the Behemoth was still on the screen, unlock the Maelstrom lock where the whole enemy group suddenly vanished.

-------

InvalidOperationException: Sequence contains no elements
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <3e4da02cf86b4fc686ed0ac61bffc210>:0)
Battle+<DoLootAsync>d__72.MoveNext () (at Assets/Scripts/RPG/Battle.cs:528)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<EndCombatAsync>d__62.MoveNext () (at Assets/Scripts/RPG/Battle.cs:312)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<BattleAsync>d__59.MoveNext () (at Assets/Scripts/RPG/Battle.cs:188)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<StartBattleAsync>d__58.MoveNext () (at Assets/Scripts/RPG/Battle.cs:169)
Rethrow as AggregateException: One or more errors occurred.
CoUtils+<TaskAsRoutine>d__9.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:96)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

**Comment by psywombats** [comment]
I thought this was related to stunning moves (STUNNER, LIGHTNING) being likely culprits but maybe not. Will have to track this down

**Comment by psywombats** [comment]
Different presentation of https://github.com/psywombats/mgne/issues/474
