### ISSUE TITLE
Analaytics null enemy party NRE

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#474]
For context: Ibis x1. Party: T-Cell (dead), T-Cell, Undine, Elf.  Used Dissolve, Rime, Tornado. Victory theme immediately played, game softlocked.

EDIT: I've had this happen now with different parties, first turn, in the middle of combat, while trying to run, after a soft reset, not after a soft reset. It's beginning to look like there's not much correlation between this exception and anything else I do.

ArgumentException
UnityEngine.Analytics.AnalyticsEvent.LevelComplete (System.String name, System.Collections.Generic.IDictionary`2[TKey,TValue] eventData) (at /Users/build/unity-packages/com.unity.analytics/Source/Unity.Analytics.StandardEvents/AnalyticsEventGenerated.cs:633)
Analytics.Victory (Battle battle) (at Assets/Scripts/Util/Analytics.cs:23)
Battle+<EndCombatAsync>d__62.MoveNext () (at Assets/Scripts/RPG/Battle.cs:307)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<BattleAsync>d__59.MoveNext () (at Assets/Scripts/RPG/Battle.cs:188)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Battle+<StartBattleAsync>d__58.MoveNext () (at Assets/Scripts/RPG/Battle.cs:169)
Rethrow as AggregateException: One or more errors occurred.
CoUtils+<TaskAsRoutine>d__9.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:96)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

**Comment by psywombats** [comment]
Pretty sure this was the same root cause as back button triggered crash caused by BLOOM refactor to targeting
