### ISSUE TITLE
Cutscene suggestion: The music should stop just as Jonas is struck down

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#477]
Also, after the fight with Lucifer, the Tower music starts up for a quick moment, probably should just come out of the fight into silence until the sad music plays.

Lastly, this is not important now, but it might be better if Aven shows up earlier. The musical progression of that cutscene is weird, going from sad dramatic moment, being interrupted by something insidious. I feel like it should be the opposite? Or maybe two separate scenes eventually?

**Comment by psywombats** [comment]
Yeah I'm not in love with this scene and I've gone through a couple internal revisions. I made the music suggestion, but I'm probably going to want to revisit this scene and do /something/ to make it less janky
