### ISSUE TITLE
World 2: Exiting the Gate Outpost from either direction puts you on top of the Gate Outpost

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#497]
On that subject, I know we had (very briefly) discussed the idea of keeping shortcut glitches or re-introducing them. This definitely qualifies as one, so it might be worth keeping in? My only concern is, how easy is it for a casual player to do on accident?

**Comment by psywombats** [comment]
Intentional so you don't have to keep walking through the empty map
