### ISSUE TITLE
Post-Prince scene suggestion: Reverse the sequence of the scene

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#684]
The scene after fighting the Prince has two sections, so to speak:

1. The heroes mourning Jonas's death

2. Aven showing up and revealing that he's an actual piece of shit

I'm suggesting the order of these two be reversed, for two reasons:

- There's a BGM that literally only plays at this part, and it's interrupted long before it even loops once
- It could give Jonas a chance to maybe be dying - rather than dead - and say some last words.

**Comment by psywombats** [comment]
aand done. I think it works better.
