### ISSUE TITLE
Design idea - "Skin" abilities should temporarily increase defense when used

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#698]
Given that monsters with these abilities (and Espers in general) are typically on the more fragile side, it's hard to justify using these abilities. Could be easier if it increases their defense by a set amount, or halves their damage taken or something.

**Comment by psywombats** [comment]
All -skin and -field abilities now double defenses. This should hopefully make them more appealing options. REVENGE also has the defense-doubling property now (lowered its power ever so slightly to compensate)
