### ISSUE TITLE
World 1 Redux: The miniboss enemy has got to change

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#707]
I can't tell you how many times I've coasted through the entire game only to get stuck here. Heathens are just too strong for this point in the game. They have tons of HP, it's dangerous to attack them with melee weapons, they're remarkably evasive, they can't be instant killed, they can't be hurt by any elements, and if they're alive for more than about two turns, they start hitting people for 400+ damage. This is the hardest fight in the game, no cap.

**Comment by psywombats** [comment]
boss fight is now `encounter_lvl09_CYCLOPS_TROOPER_HOMUNCULUS`
