### ISSUE TITLE
The enemies from the Ares fight make the Bestiary angry

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#708]
The exceptions occur when hovering over the Bestiary option; game freezes upon selection.

![Screenshot 2022-06-11 21 26 13](https://user-images.githubusercontent.com/60168946/173214441-c30e8ba8-0637-4b0f-b6ac-5d33e2fdb416.png)

**Comment by psywombats** [comment]
keyed with the wrong field sprite
