### ISSUE TITLE
If you soft reset within a few frames of triggering a random battle, the title screen fades to white instead

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#711]
Also came with this exception message. You can fix it by soft resetting again.

---------------------

MissingReferenceException: The object of type 'MeshRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Renderer.GetPropertyBlock (UnityEngine.MaterialPropertyBlock properties) (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
MaterialEffectComponent+<AnimateRoutine>d__11.MoveNext () (at Assets/Scripts/Graphics/MaterialEffectComponent.cs:40)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
I put in a fix for this, but, it's not possible for me to repro so I'm unsure if it's solved. And if this doesn't solve it, I'm not sure I'll be able to fix it at all -- it's very similar to a longstanding bug I have in my work project that no one's been able to puzzle out
