### ISSUE TITLE
NRE when using RAISE

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#721]
Not sure if using RAISE always causes an NRE (because I rarely ever use it), or if it has something to do with the context (Lucifer boss, used RAISE on Janine who of course joins midway through)

------------

NullReferenceException: Object reference not set to an instance of an object
DollArea+<AnimateEffectRoutine>d__24.MoveNext () (at Assets/Scripts/UI/Battle/DollArea.cs:144)
IEnumeratorAwaitExtensions+CoroutineWrapper`1+<Run>d__3[T].MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:254)
--- End of stack trace from previous location where exception was thrown ---
IEnumeratorAwaitExtensions+SimpleCoroutineAwaiter`1[T].GetResult () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:152)
BattleAnimShaderOld.PlayInternalAsync (BattleView view, System.Collections.Generic.List`1[T] targets) (at Assets/Scripts/Graphics/BattleAnimation/BattleAnimShader.cs:15)
BattleAnim.PlayAsync (BattleView view, System.Collections.Generic.List`1[T] targets, System.Boolean mute) (at Assets/Scripts/Graphics/BattleAnimation/BattleAnim.cs:32)
EffectRevive.PlayBattleAnimAsync (Intent intent) (at Assets/Scripts/RPG/Effects/EffectRevive.cs:92)
EffectRevive.ResolveAsync (Intent intent) (at Assets/Scripts/RPG/Effects/EffectRevive.cs:66)
Intent.ResolveAsync () (at Assets/Scripts/RPG/Intent.cs:100)
Battle.ResolveIntentsAsync () (at Assets/Scripts/RPG/Battle.cs:461)
Battle.FightAsync (System.Boolean playerCanAct) (at Assets/Scripts/RPG/Battle.cs:332)
Battle.BattleAsync () (at Assets/Scripts/RPG/Battle.cs:257)
Battle.StartBattleAsync () (at Assets/Scripts/RPG/Battle.cs:240)
Battle.BattleAsync (BattleView view) (at Assets/Scripts/RPG/Battle.cs:213)
BattleView.SpawnBattleAsync (BattleOptions options) (at Assets/Scripts/UI/Battle/BattleView.cs:223)
Rethrow as AggregateException: One or more errors occurred. (Object reference not set to an instance of an object)
CoUtils+<TaskAsRoutine>d__10.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:109)
IEnumeratorAwaitExtensions+CoroutineWrapper`1+<Run>d__3[T].MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:254)
--- End of stack trace from previous location where exception was thrown ---
IEnumeratorAwaitExtensions+SimpleCoroutineAwaiter`1[T].GetResult () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:152)
LuaContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:85)
LuaCutsceneContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaCutsceneContext.cs:37)
LuaContext.RunRoutineFromLua (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:78)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
Caused by the revive animation trying to animate on the player
