### ISSUE TITLE
Edenic World Minor Issues

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#722]
- Battle music does not play
- GIANT has no sprite data
- In the Palace of the Gods, there's no way to return to the main hall after going down the route to Ares; you have to use an exit item or you're stuck.
- The DEFIBRILLATOR item can only be used on the Robot.

**Comment by psywombats** [comment]
- key was set incorrectly in bgm index
- GIANT bug has been around since SaGa4 it seems
- added a missing staircase on the right from f2 to f3
- projector was set to USER instead of ALLY
