### ISSUE TITLE
Missing encounters *somewhere*

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#726]
Played through the Tower leading up to Gamma World, noticed it some time while in Gamma World. Not sure when it first appeared. Does not seem to have any effect on gameplay.

----------------------------------

NullReferenceException: Object reference not set to an instance of an object
TerrainEncounterSet.get_AverageStepsToEncounter () (at Assets/Scripts/RPG/TerrainEncounterSet.cs:18)
BaseEncounterSet.CheckForEncounterOnStep () (at Assets/Scripts/RPG/BaseEncounterSet.cs:40)
Map.Avatar_OnStepEnded (System.Boolean collided) (at Assets/Scripts/Map/Map.cs:283)
AvatarEvent.FinishStep (System.Collections.Generic.List`1[T] toCollide) (at Assets/Scripts/Map/AvatarEvent.cs:317)
AvatarEvent+<>c__DisplayClass44_0.<TryStep>b__1 () (at Assets/Scripts/Map/AvatarEvent.cs:260)
CoUtils+<RunWithCallback>d__5.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:50)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
Think this was caused by new default encounter sets, so you were probably on a non-standard tile somewhere
