### ISSUE TITLE
Edenic World: Zkauba's prefight dialogue displays incorrectly, possibly BORG's as well.

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#738]
So, when you take Janine or Lara, they have a line near the beginning of the conversation, and a line near the end of the conversation. However...

- When you take BORG, the first line is replaced by one of your main party members.
- When you take Zkauba, the first line is replaced by one of your main party members, and the second line is BORG's line.

**Comment by psywombats** [comment]
Typo in the switch check for the second variable line. BORG doesn't speak the first one because they have no personal relationship with Aven.
