### ISSUE TITLE
Last-minute idea: Implement PUNCH?

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#739]
This seemed difficult to implement before when there were just two buttons...but what if in the combat menus, pressing the jump button automatically executed a PUNCH? This would give characters who run out of charges a way to impact the fight, however small. It also makes less sense than imagining that they would just sit there. Let me know what you think.

**Comment by psywombats** [comment]
I'd probably only make it visible/selectable when there was literally no other option. Maybe worth doing, although I've never had this happen.
