### ISSUE TITLE
Poison might have a damage cap, on either a per-target or per-fight basis?

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#740]
I know I asked about this before, but just to clarify: does Poison not work on a boss after it has dealt damage equal to 50% of their HP? When I did my Monster run, after a certain point in the boss fight, Poison would always wear off on the same turn I applied it. If this is intended, then it might do to have some sort of system message about it so that players stop trying to apply it. If it's not intended, I would look into it.

**Comment by psywombats** [comment]
If this is happening, it's a bug

**Comment by psywombats** [comment]
This was happening because of some ancient status logic around turn-limited conditions.
