### ISSUE TITLE
We might want to disable the menu when in the middle of a step

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#743]
Something I tried today:

- I know that when you take one step south in Rivertown after the Airseed Shrine, it will trigger a dialogue with David and he will leave the party.

- I entered Rivertown, took a step south, and saved before the cutscene could trigger.

- I soft reset, loaded the game, and was on the proper tile, but the cutscene didn't start until I moved off of it and back onto it.

This wasn't a HUGE deal, because it seems that Plainstown being destroyed is tied to David leaving the party...but there might potentially be places where this is abusable down the line (I'm now wondering if you can skip all of Castle Ares and go straight to the boss fight with this, for example).

On the other hand, if you want to leave the glitch in and see if speedrunners do anything with it, be my guest.

**Comment by SkankinGarbage** [comment]
Current list of things I've been able to do with this glitch:

1. The first time going through the Red Tower, you can slip past the trigger for the first Moloch fight and grab the Red Shard early.
2. You can skip the boss battle against SET.

**Comment by psywombats** [comment]
New expected behavior:
Trying to pause while stepping brings up the pause menu after the step is complete, unless the step results in a cutscene being played, in which case the menu request is canceled altogether.
