### ISSUE TITLE
Polish: The opening room of the tower

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#747]
1. It feels very weird to get into random battles here, when we're trying to hammer home how mysterious it is.

2. Whenever we do a closed beta, I'd love to hear feedback on which side of the portal they think you should be on upon entry. It always, always confuses me, even after so many playthroughs. But, I also know that the exit is to the south already, so I'm not sure if that's a big part of why.

**Comment by psywombats** [comment]
Random encounters are now disabled until the initial cutscene, and I removed a gap that should make it more obvious to head south
