### ISSUE TITLE
World 3: The final room of Mt. Hali has no assigned battle background

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#751]
The room with the jail cell and stuff.

**Comment by SkankinGarbage** [comment]
Piggybacking on this issue: You can get into random battles in the final room of the power plant (where you fight the boss), and there's no battle background associated with the random battles here, either.

**Comment by psywombats** [comment]
Removed encounters from powerplant05.tmx and added the cave backdrop to hali4.tmx

**Comment by SkankinGarbage** [comment]
Ahaha, whoopsies...This map also has no assigned battle background:
![Screenshot 2022-08-04 11 50 07](https://user-images.githubusercontent.com/60168946/182930643-fefd43f7-576f-4da7-a22e-574910d80340.png)

**Comment by SkankinGarbage** [comment]
2ND EDIT: Getting into a fight on the monorail tiles in the world map also has no battle background.

**Comment by psywombats** [comment]
Should now have cliffs and plains battlebacks, respectively.
