### ISSUE TITLE
UPDATE: Enemy monsters that can heal can bring dead enemies in dead groups back to life

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#752]
- Found 1 JIANSHI, 4 HORNET.
- Killed the JIANSHI with a WHITE sword.
- Was killing the HORNETS with SAWs, when suddenly, the JIANGSHI re-appeared.
- Can't remember if the SAW hit or not, but given my Robot's strength stat, I don't think it failed on the HORNETs.
- Can't remember anything else noteworthy.

I took a screenshot of my party, if you want to try and use it to repro this bug.

**Comment by SkankinGarbage** [comment]
EDIT: I saw the issue more clearly on this playthrough. I killed a JIANGSHI, and a Hornet used HONEY on it.

1. No sound effect was played for HONEY
2. The JIANGSHI suddenly re-appeared and could be attacked.

I've seen this with other enemy groups, although I don't remember which. It's safe to say, though, that it was probably any enemy group that could heal.

**Comment by psywombats** [comment]
Yep, definitely a targeting bug here. Should be resolved.
