### ISSUE TITLE
World 1 Redux: The Howling Cave is already pitch-black upon entry

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#753]
There's also an error message:

----------------------

ArgumentException: An item with the same key has already been added. Key: blackout
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
BlackoutComponent.Start () (at Assets/Scripts/Map/BlackoutComponent.cs:24)

**Comment by psywombats** [comment]
Related to some lighting code used in last cutscene -- might be fixed now but warrants investigation

**Comment by psywombats** [comment]
May require a reimport
