### ISSUE TITLE
SAMURAI gauntlets only give +36 Robo-HP

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#759]
Besides the error to the SMG (didn't grant STR), the FIRE gun (gives Tier 3 stats but is a Tier 2 weapon), and MURAMASA (doesn't grant tier 10 HP), I've found two other ones:

1. SAMURAI gauntlets: 

- Does not actually grant any defense
- Only grants +36 Robot HP
- Grants +10 STR and +AGI to wearer (found under item info, but not listed in the tooltip)

2. DRAGON helmet:

- Does not grant fire resistance

It might be useful to look over the database of items and make sure they're all doing what they are supposed to. I'll do my best to check, but there are just so many items I don't use with any party.

**Comment by psywombats** [comment]
Fixed both in DB
