### ISSUE TITLE
World 1 Redux: Some cutscene polish suggestions

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#765]
These are very minor things that I don't think you necessarily have to address. But, I think they can help with immersion if you do.

1. When Janine shows your party the MASAMUNE, you don't see a sword, or any sort of special effects animation. Even now, this always throws me for a loop because I hear the sound effect and forget that it's not a glitch. (On the subject, it would be good if some sort of effects animation were added to the opening of the gates, as with opening the Gamma World gate with the MURAMASA, and Janine opening the final gate at the top of Babel.)

2. When first receiving the FLASHLIGHT, it would be better for the sake of comedic timing if the text box was automated to end and fade to white as the sound effect comes to a crescendo.

3. When going to the basement in Castle Ares, it would be better if the cutscene activated at the bottom of the stairs - a bit more sensible from the perspective of the party (when they finally reach the lower level is when they're most likely to comment on it if it were real), but also, it lets the player notice more easily that it's getting dark. (If you decide to make this change, the same adjustment as to where the dialogue triggers should be changed for when you go to Castle Ares without the FLASHLIGHT as well.)

4. Not exactly cutscene polish, but it seems related: Janine has the MASAMUNE. ...Janine does not use the MASAMUNE in combat.

5. Similar to the first point, there's no animation when Janine destroys the AEGIS.

**Comment by psywombats** [comment]
Implemented 4 -- it does the same damage as the original E-SABER.

Moved the trigger for 3

I'm really not interested in implementing textbox speed controls to slightly improve the joke in 2

1 and 5 are low priority art requests and unlikely to happen
