### ISSUE TITLE
World 5: You can avoid the first ISHRA fight by using a RETURN

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#766]
Granted, this doesn't technically break the game, cos the scene will trigger when you come back. But it does mean that the nearest usable inn is several floors down the tower, so it could lead to some obnoxious situations.

EDIT: You can also miss the Zomi cutscene by leaving out of any other exit tile besides the ones at the front gate.

**Comment by psywombats** [comment]
Actually I think I'm fine with this one as it allows a "surprise" fight to be escaped, if for some reason the party is totally broken. It's not a particularly difficult fight that not having the inn right there is a huge problem
