### ISSUE TITLE
Polish: Reconsider super-large groups of enemy JELLYFISH

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#769]
Paralyzes galore, heals galore, used 5 DEATH FANGs, all 5 charges of CHILL, all 3 charges of FLAME, broke two RAPIERS with ~10 charges left...just couldn't kill the last three. I realize you can run away...but this fight is just kind of annoying.

**Comment by psywombats** [comment]
Trimmed this group to 4-5 rather than 5-7. This is an encounter meant to punish magic-heavy parties though (jellyfish have a defense of 4)
