### ISSUE TITLE
LONG bow stays in equipment at 0 charges when equipped to Espers

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#770]
- Maybe also Humans?
- Maybe every bow?

EDIT: THUNDER Staff had the same problem. This might be a coincidence, but it's been on the main character (Esper F) both times. Many other weapons have been removed from equipment upon breaking as expected.

EDIT 2: ICE Staff, again, on the main character. Unsure if it's that it's the main character, or the front character, or if the race has something to do about it. I don't remember having this issue before, but I know a bug was recently fixed concerning weapons with 0 charges, so that also might have something to do with it.

EDIT 3: Nevermind, Stone staff also did it on the third character, so it has nothing to do with being the main or front character. For what it's worth, the third character in my group is also an Esper F.

**Comment by psywombats** [comment]
This cropped up after the depletion fix for robots, yeah -- mutants were treating all slots as ability slots for this purpose
