### ISSUE TITLE
NRE When stepping on spikes (no gameplay freeze, no obvious impact on gameplay)

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#772]
NullReferenceException: Object reference not set to an instance of an object
Map.<Avatar_OnStepEnded>b__69_0 () (at Assets/Scripts/Map/Map.cs:280)
CoUtils+<RunWithCallback>d__5.MoveNext () (at Assets/Scripts/Util/CoUtils.cs:50)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
happened in cases with no encounters defined
