### ISSUE TITLE
"Continuous BGM Playback" feedback

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#779]
1. It's weird when the music fades out as battle starts...only to fade back in as the same track.

2. Victory theme should be disabled, or it's not really continuous playback. 

Here's a very clear example:
https://youtu.be/Hn7QxHbxzPU?t=439

3. Charnel World seems like a good place to use continuous bgm playback, by the way!

**Comment by psywombats** [comment]
1. The fade is now only to 50% (for the encounter sfx)
2. done
3. done
