### ISSUE TITLE
New text error/text oddity/other oddities pass

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#781]
Some of these might have been fixed already, but I'm pretty sure all of these are from my final set of runs, so it's unlikely.

1. Every time I see this, I just think, "What on earth is he talking about!?" this might be an obvious thing, so if it is, I guess don't worry about it.

![Screenshot 2022-06-11 23 36 53](https://user-images.githubusercontent.com/60168946/184510555-a977ebec-5419-425b-8809-35f7ab271413.png)

2 "the" Moloch

![Screenshot 2022-06-12 11 51 05](https://user-images.githubusercontent.com/60168946/184510583-8851e956-39b5-47ec-b375-904cf208036e.png)

3. will protected the gate

![Screenshot 2022-06-22 17 40 15](https://user-images.githubusercontent.com/60168946/184510602-f7f527f6-f7ab-4b7a-88f6-714e99498e64.png)
 
 
 4. Non-text related: You can see a random wall, here. This happens in a few other places, but this is the one I always remember. 
 
![Screenshot 2022-07-31 00 20 32](https://user-images.githubusercontent.com/60168946/184510635-25e90679-0419-49ce-827c-ee403e76b910.png)
 

5. Non-text related: If you reflect MAGMA back at an enemy and then kill them, this sometimes happens. This possibly could happen from just casting MAGMA, too; but somehow, I've never, ever gotten MAGMA on any character in any run - I only recently found out that it had a unique animation.

![Screenshot 2022-08-01 13 03 00](https://user-images.githubusercontent.com/60168946/184510660-68cdfac8-4865-4fb6-96d7-47d9a75ea126.png)
 
 
 6. This started happening in the Lucifer fight. I don't know if it's a coincidence or not, but this was the first run where I put the MURAMASA on someone that wasn't the main character. I also didn't put the MURAMASA on a main character in any of my runs after this, so I can't say with certainty that this has anything to do with it.
 
![Screenshot 2022-08-01 17 13 51](https://user-images.githubusercontent.com/60168946/184510687-9a9e2083-7d42-45d4-a913-d514db022a47.png)
 
 
 7. City of Angel
 
![Screenshot 2022-08-10 14 27 24](https://user-images.githubusercontent.com/60168946/184510747-2a31e3da-3d6f-49e5-a2c2-0352a651a6ee.png)

**Comment by psywombats** [comment]
6 was caused by a change to the quote method for Aven. 5 I think was caused by a misconfiguration of the animation (set to not reset sprites)
