### ISSUE TITLE
Autosave pointer isn't working right

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#783]
keeps trying to load one slot below or something?

**Comment by SkankinGarbage** [comment]
Save/load pointers in general (if I understand what you mean) are a little wonky. When you load a game, it always points to the bottom save file...which would be fine, except for that when you go to save, it points to the most recent save that was made, which isn't always the same file. If the logic were consistent in either direction (either "load points to most recent save" or "save points to bottom file"), that would be a little easier. The first one is probably better, though.

**Comment by psywombats** [comment]
was caused with the new save preview system
