### ISSUE TITLE
Aven bugs that can be demonstrated with screenshots

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#784]
Error 1: I have no party members named "2":

![Screenshot 2022-10-03 12 31 04](https://user-images.githubusercontent.com/60168946/193672259-c6c0f002-e584-43c1-a84b-e75399fb9a17.png)

Error 2: "Unit does nothing." The boss didn't take any actions this turn. I have a suspicion that this might happen when it tries to use AEON on a dead target, but I can't say for sure. 

![Screenshot 2022-10-03 12 59 19](https://user-images.githubusercontent.com/60168946/193672655-26117576-35b0-405b-a431-e6a784a752f9.png)

**Comment by psywombats** [comment]
fixed'd
