### ISSUE TITLE
Other Aven bugs/potential issues

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#790]
- Aven might be healing too much on Rudra phase
- The strategy for Rudra phase and Ares phase might be the same? But I haven't checked what happens if you just try to end Ares phase early by burning the boss.
- Lucifer's battle sprite doesn't despawn on death
- Great Sage keeps spamming Zenith near the end of the fight. By the way, should he be able to enter that phase while the party is affected by Aeon?

**Comment by psywombats** [comment]
1. Halved healing chance when Aven is the only one remaining
2. Not an issue as all members must be killed (and can revive)
3. Known issue, will fix when this fight as real graphics/animations
4. Should be fixed. I hadn't anticipated entering this while under Aeon but it shouldn't be too big of a deal as there are two turns to recover
