### ISSUE TITLE
Confusing menu/inventory glitch - using a consumable sometimes takes you out of the inventory menu

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#794]
How to reproduce:

1. Open the menu

2. Select inventory. If you use a consumable at this point, you the cursor will still move up and down in your inventory - in other words, working as intended, I assume.

3. Press cancel to move the cursor back to the main menu.

4. Select inventory again. Now, if you use a consumable item, the next time you try to move the cursor, it will move up and down in the main menu instead of your inventory. This persists until you leave the menu screen.

**Comment by psywombats** [comment]
the closed flag wasn't being unset when the minimenu was shown
