### ISSUE TITLE
ARCANE can't restore charges to items previously equipped by a robot

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#796]
I'm unsure what's intended, here. But, if you remove, say, a MASAMUNE from a robot, and try to fix it with an Arcane, nothing happens (even though it still says that the max charges are 50). I'm leaning towards making this possible, since even though it's sort of a "workaround", it costs a damn lot of money to do. But, I don't know how difficult it would be to implement it without messing up how equipment works for Robots.

**Comment by psywombats** [comment]
turns out all unequipped items in general were affected
