### ISSUE TITLE
SAMURAI Gauntlets only grant +36 HP to Robots

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#797]
Not sure if this is intended, but it seems awfully low for an endgame piece or armor. It would also certainly go a long way in explaining why my Robot party has far-and-away the lowest max HP values out of all other parties. (Granted, they still would have the lowest HP, but not by such an extreme amount.)

**Comment by psywombats** [comment]
fixed in a balance patch somewhere
