### ISSUE TITLE
World 1 Redux: River Town needs to be looked at

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#803]
Almost every teleport is a wrong warp or the exit doesn't work, and entering the down normally (without a DOOR) puts you way out of bounds (there are also NPCs out of bounds as well).

**Comment by psywombats** [comment]
my bad yeah, I did not test this or mountain town

**Comment by psywombats** [comment]
was in the 3.5 version which is why I didn't notice
