### ISSUE TITLE
Choosing to go back to the title screen after losing is massively bugged

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#805]
1. Sometimes, the title screen music is replaced with the BGM of the place where you lost (this seems to be tied to going back to the title screen after viewing bad endings)
2. If you start a new game afterwards, it still has all the data from your previous party, including flags triggered, party members, inventory, etc.:

![Screenshot 2022-11-09 11 41 02](https://user-images.githubusercontent.com/60168946/200926206-c42c2151-ee42-407a-93d5-dfa2d39bd66b.png)
![Screenshot 2022-11-09 11 42 42](https://user-images.githubusercontent.com/60168946/200926210-e3c9e475-71f4-4d44-b0d8-7dd28731d667.png)

---------------------------
NullReferenceException: Object reference not set to an instance of an object
LuaCutsceneContext+<RunRoutine>d__1.MoveNext () (at Assets/Scripts/Lua/LuaCutsceneContext.cs:21)
IEnumeratorAwaitExtensions+CoroutineWrapper`1+<Run>d__3[T].MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:254)
--- End of stack trace from previous location where exception was thrown ---
IEnumeratorAwaitExtensions+SimpleCoroutineAwaiter`1[T].GetResult () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:152)
LuaContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:85)
LuaCutsceneContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaCutsceneContext.cs:42)
LuaContext.RunRoutineFromLua (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:78)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
wasn't resetting the game properly
