### ISSUE TITLE
World 1: In the Airseed shrine, you can jump over the miniboss and get the SCUBA without fighting them/Bandit fight locks the game

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#807]
Not a massive sequence break or anything, since it seems that the flag for opening the southwestern cave is tied to something else.

EDIT: That said, if you jump over the bandits on the side and talk to the middle one, the game locks.
EDIT2: Wait I lied, there just seems to be an issue with that encounter starting.
----

NullReferenceException: Object reference not set to an instance of an object
LuaCutsceneContext+<RunRoutine>d__1.MoveNext () (at Assets/Scripts/Lua/LuaCutsceneContext.cs:21)
IEnumeratorAwaitExtensions+CoroutineWrapper`1+<Run>d__3[T].MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:254)
--- End of stack trace from previous location where exception was thrown ---
IEnumeratorAwaitExtensions+SimpleCoroutineAwaiter`1[T].GetResult () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:152)
LuaContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:85)
LuaCutsceneContext.RunRoutineFromLuaInternal (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaCutsceneContext.cs:42)
LuaContext.RunRoutineFromLua (System.Collections.IEnumerator routine) (at Assets/Scripts/Lua/LuaContext.cs:78)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
The battle start issues were likely the unit index. Jumpability stuff should also be resolved.
