### ISSUE TITLE
Palace of the Gods: Moloch's chest can't be opened

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#808]
Two exceptions:

------------

Scriptable index CombatItemIndex does not contain armor_arthur
UnityEngine.Debug:LogError (object)
ScriptableObjectIndex`2<CombatItemData, ScriptableObjectReference>:GetData (string) (at Assets/Scripts/Data/Indices/Generic/ScriptableObjectIndex.cs:71)
ChestComponent/<OpenAsync>d__25:MoveNext () (at Assets/Scripts/Map/ChestComponent.cs:128)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<ChestComponent/<OpenAsync>d__25> (ChestComponent/<OpenAsync>d__25&)
ChestComponent:OpenAsync ()
ChestComponent:OnInteract (AvatarEvent) (at Assets/Scripts/Map/ChestComponent.cs:104)
ChestComponent:<Start>b__20_0 (object) (at Assets/Scripts/Map/ChestComponent.cs:71)
Dispatch:Signal (string,object) (at Assets/Scripts/Util/Dispatch.cs:45)
AvatarEvent:Interact () (at Assets/Scripts/Map/AvatarEvent.cs:297)
AvatarEvent:OnCommand (InputManager/Command,InputManager/Event) (at Assets/Scripts/Map/AvatarEvent.cs:129)
InputManager:Update () (at Assets/Scripts/IO/InputManager.cs:91)

**Comment by SkankinGarbage** [comment]
NullReferenceException: Object reference not set to an instance of an object
CombatItem..ctor (CombatItemData data) (at Assets/Scripts/RPG/CombatItem/CombatItem.cs:54)
ChestComponent.OpenAsync () (at Assets/Scripts/Map/ChestComponent.cs:128)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
needed to set the key correctly; fixed
