### ISSUE TITLE
Trying to move or equip anything in the inventory below the 14th slot locks the game

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#812]
I'm not certain, but I think the culprit might be the cursors in the menu. If I'm at the top of the menu and select the top item, a cursor will stay floating over Item1 while I select another inventory slot with a second cursor. However, if you're paged down from the top of the menu at all, the "reminder" cursor will be offset a number of spaces downward in the inventory menu.

Here's the exception text - both of the 'ItemMenuView' values change depending on which of the offending slots the item is in when triggered. If you need a video of this, let me know.

----

UnityException: Transform child out of bounds
DynamicListSelector.GetCell (System.Int32 index) (at Assets/Scripts/UI/ListSelector/DynamicListSelector.cs:22)
ItemMenuView.SwapForSlot (System.Int32 slot1) (at Assets/Scripts/UI/Menus/ItemMenuView.cs:153)
ItemMenuView.DoMenuAsync (MainMenuView parent) (at Assets/Scripts/UI/Menus/ItemMenuView.cs:73)
MainMenuView.ItemSelect () (at Assets/Scripts/UI/Menus/MainMenuView.cs:115)
MainMenuView.MenuAync () (at Assets/Scripts/UI/Menus/MainMenuView.cs:68)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <7b935204f5ff4bcab44b3b0ebca330bf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <ab7de6937a4448b0a6ccd59e9820599a>:0)

**Comment by psywombats** [comment]
was caused by having a scroll offset
