### ISSUE TITLE
Epilogue Stuff

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#814]
1. There are multiple copies of the endgame NPCs when you first return from the Final Gate.

![Screenshot 2022-11-20 14 33 11](https://user-images.githubusercontent.com/60168946/202929925-d8cc3c14-122d-4657-866b-689f6559f19b.png)

2. This isn't a glitch, per se...but Janine (or BORG, if Janine is in the party) always calls out the name of the front character. This can create a pretty impersonal cry from Janine, of all people.

![Screenshot 2022-11-20 14 36 44](https://user-images.githubusercontent.com/60168946/202930074-29e0be3f-459b-435b-a514-fab5c37b7340.png)

3. When talking to the main NPCs during the epilogue, it's probably worth giving them a second, much shorter piece of dialogue for when you talk to them a second time.

4. You can leave the Epilogue using a DOOR or RETURN. This doesn't break the game, since there's no flag to make Aven despawn from the Final Gate...but it sure is weird.

5. I think beginning the Epilogue text crawl with a sentence so similarly to the beginning of the intro's text crawl is a bit confusing. I didn't realize at first that it was even different; I just assumed it was C/P'ed as placeholder text.

6. As discussed, this could probably use some credits.

7. Not properly explained what exactly is happening/happened to Babel in the dialogue just after returning from Aven's defeat. The epilogue implies that it still seems to be intact, and that worlds can be traveled to and from with no issue.

8. Not adequately explained what the party leaves to do in the end? I suppose this could be inferred from the conversation with the Elder; but you could just as easily leave without ever talking to him.

Otherwise...dialogue looks fine (no errors), game properly accounts for who's in the party (even a four-person party), and the endgame reset seems to work as intended (the chests don't reset, but I assume that's on purpose).

**Comment by psywombats** [comment]
1. fixed on map
2. should be fixed for new save files now that 5th party members aren't assigned a story slot
3. done
4. should be disabled after the bossfight now
5. intentional parallel, unlikely to change
6. TODO
7. TODO, not sure how to explain the w5 is falling apart but babel is fine -- it isn't hugely sensible to begin with
8. not so worried here... this is more a problem that it isn't clear to me either

**Comment by psywombats** [comment]
6. done
7. Updated the finale script after the bossfight to imply that it's Eden collapsing, not Babel in general.
