### ISSUE TITLE
Final World: If you fight Aven with no guest party members, BORG somehow chimes in anyways

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#815]
BORG is not in the party in this screenshot...nor is Janine, Lara, or Zkauba.

![Screenshot 2022-11-20 14 39 51](https://user-images.githubusercontent.com/60168946/202930764-a8ec3c5e-a5bf-458e-b62d-ad75338ae12f.png)

**Comment by psywombats** [comment]
needed another `if`
