### ISSUE TITLE
Final World: During the final sequences, the world map theme starts up at many inappropriate times

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#819]
1. In the scene transition between the first and second Aven fights

2. If you save immediately after defeating GREAT SAGE and reload the game, the world map theme starts up

3. When you leave the Final Gate and get teleported to the Final Town. Unlike the other two, however, where silence would be appropriate, this could probably use a specific track (maybe Emergency? Or even reprise the final battle theme, depending on how dramatic you want that part to be)

**Comment by psywombats** [comment]
I put Emergency in, per suggestion
