### ISSUE TITLE
Final Boss/Ending stuff - second pass

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#823]
1. Showing the standard victory notice after beating the last boss is kind of weird, buuut it's a thing in all the game boy games, so I don't mind. What IS still kind of weird though, is how Espers can get mutations after beating the last battle. Is there a way to disable that?

2. two console Errors. Basically, the Epilogue music doesn't play, but the standard Town Theme DOES play if you enter a building. If there was supposed to be a music change in the credits, it doesn't happen.

Here's the first error. Second one is in the replies:

--------------

Index BGMIndexData does not contain key"epilogue"
UnityEngine.Debug:LogError (object)
DebugPanel:LogError (string) (at Assets/Scripts/Util/DebugPanel.cs:66)
SerializableObjectIndex`1<BGMData>:GetData (string) (at Assets/Scripts/Data/Indices/Generic/SerializableObjectIndex.cs:23)
AudioManager:PlayBGM (string) (at Assets/Scripts/Audio/AudioManager.cs:81)
Map:OnTeleportTo () (at Assets/Scripts/Map/Map.cs:236)
MapManager:RawTeleport (Map,UnityEngine.Vector2Int,System.Nullable`1<OrthoDir>) (at Assets/Scripts/Map/MapManager.cs:148)
MapManager:RawTeleport (string,string,System.Nullable`1<OrthoDir>) (at Assets/Scripts/Map/MapManager.cs:120)
MapManager/<TeleportRoutine>d__26:MoveNext () (at Assets/Scripts/Map/MapManager.cs:96)
IEnumeratorAwaitExtensions/CoroutineWrapper`1/<Run>d__3<object>:MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:254)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
IEnumeratorAwaitExtensions/<>c__DisplayClass12_0:<GetAwaiter>b__0 () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:93)
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:118)
IEnumeratorAwaitExtensions:GetAwaiter (System.Collections.IEnumerator) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:93)
LuaContext/<RunRoutineFromLuaInternal>d__17:MoveNext () (at Assets/Scripts/Lua/LuaContext.cs:85)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<LuaContext/<RunRoutineFromLuaInternal>d__17> (LuaContext/<RunRoutineFromLuaInternal>d__17&)
LuaContext:RunRoutineFromLuaInternal (System.Collections.IEnumerator)
LuaCutsceneContext:<>n__1 (System.Collections.IEnumerator)
LuaCutsceneContext/<RunRoutineFromLuaInternal>d__3:MoveNext () (at Assets/Scripts/Lua/LuaCutsceneContext.cs:41)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<LuaCutsceneContext/<RunRoutineFromLuaInternal>d__3> (LuaCutsceneContext/<RunRoutineFromLuaInternal>d__3&)
LuaCutsceneContext:RunRoutineFromLuaInternal (System.Collections.IEnumerator)
LuaContext/<RunRoutineFromLua>d__16:MoveNext () (at Assets/Scripts/Lua/LuaContext.cs:78)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<LuaContext/<RunRoutineFromLua>d__16> (LuaContext/<RunRoutineFromLua>d__16&)
LuaContext:RunRoutineFromLua (System.Collections.IEnumerator)
LuaCutsceneContext:TargetTeleport (MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue) (at Assets/Scripts/Lua/LuaCutsceneContext.cs:131)
(wrapper dynamic-method) object:lambda_method (System.Runtime.CompilerServices.Closure,object,object[])
MoonSharp.Interpreter.Interop.MethodMemberDescriptor:Execute (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) (at Assets/Plugins/MoonSharp/Interpreter/Interop/StandardDescriptors/ReflectionMemberDescriptors/MethodMemberDescriptor.cs:195)
MoonSharp.Interpreter.Interop.FunctionMemberDescriptorBase/<>c__DisplayClass29_0:<GetCallback>b__0 (MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) (at Assets/Plugins/MoonSharp/Interpreter/Interop/StandardDescriptors/MemberDescriptors/FunctionMemberDescriptorBase.cs:83)
MoonSharp.Interpreter.CallbackFunction:Invoke (MoonSharp.Interpreter.ScriptExecutionContext,System.Collections.Generic.IList`1<MoonSharp.Interpreter.DynValue>,bool) (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/CallbackFunction.cs:58)
MoonSharp.Interpreter.Execution.VM.Processor:Internal_ExecCall (int,int,MoonSharp.Interpreter.CallbackFunction,MoonSharp.Interpreter.CallbackFunction,bool,string,MoonSharp.Interpreter.DynValue) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:720)
MoonSharp.Interpreter.Execution.VM.Processor:Processing_Loop (int) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:115)
MoonSharp.Interpreter.Execution.VM.Processor:Coroutine_Resume (MoonSharp.Interpreter.DynValue[]) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_Coroutines.cs:54)
MoonSharp.Interpreter.Coroutine:Resume (MoonSharp.Interpreter.DynValue[]) (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/Coroutine.cs:142)
MoonSharp.Interpreter.Coroutine:Resume () (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/Coroutine.cs:179)
LuaContext:ResumeAwaitedScript () (at Assets/Scripts/Lua/LuaContext.cs:149)
LuaContext/<RunRoutineFromLuaInternal>d__17:MoveNext () (at Assets/Scripts/Lua/LuaContext.cs:87)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:118)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<object>:Complete (object,System.Exception) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:170)
IEnumeratorAwaitExtensions/CoroutineWrapper`1/<Run>d__3<object>:MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:284)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by SkankinGarbage** [comment]
Index BGMIndexData does not contain key"ending"
UnityEngine.Debug:LogError (object)
DebugPanel:LogError (string) (at Assets/Scripts/Util/DebugPanel.cs:66)
SerializableObjectIndex`1<BGMData>:GetData (string) (at Assets/Scripts/Data/Indices/Generic/SerializableObjectIndex.cs:23)
AudioManager:PlayBGM (string) (at Assets/Scripts/Audio/AudioManager.cs:81)
LuaCutsceneContext:PlayBGM (MoonSharp.Interpreter.DynValue) (at Assets/Scripts/Lua/LuaCutsceneContext.cs:112)
(wrapper dynamic-method) object:lambda_method (System.Runtime.CompilerServices.Closure,object,object[])
MoonSharp.Interpreter.Interop.MethodMemberDescriptor:Execute (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) (at Assets/Plugins/MoonSharp/Interpreter/Interop/StandardDescriptors/ReflectionMemberDescriptors/MethodMemberDescriptor.cs:195)
MoonSharp.Interpreter.Interop.FunctionMemberDescriptorBase/<>c__DisplayClass29_0:<GetCallback>b__0 (MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) (at Assets/Plugins/MoonSharp/Interpreter/Interop/StandardDescriptors/MemberDescriptors/FunctionMemberDescriptorBase.cs:83)
MoonSharp.Interpreter.CallbackFunction:Invoke (MoonSharp.Interpreter.ScriptExecutionContext,System.Collections.Generic.IList`1<MoonSharp.Interpreter.DynValue>,bool) (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/CallbackFunction.cs:58)
MoonSharp.Interpreter.Execution.VM.Processor:Internal_ExecCall (int,int,MoonSharp.Interpreter.CallbackFunction,MoonSharp.Interpreter.CallbackFunction,bool,string,MoonSharp.Interpreter.DynValue) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:720)
MoonSharp.Interpreter.Execution.VM.Processor:Processing_Loop (int) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_InstructionLoop.cs:115)
MoonSharp.Interpreter.Execution.VM.Processor:Coroutine_Resume (MoonSharp.Interpreter.DynValue[]) (at Assets/Plugins/MoonSharp/Interpreter/Execution/VM/Processor/Processor_Coroutines.cs:54)
MoonSharp.Interpreter.Coroutine:Resume (MoonSharp.Interpreter.DynValue[]) (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/Coroutine.cs:142)
MoonSharp.Interpreter.Coroutine:Resume () (at Assets/Plugins/MoonSharp/Interpreter/DataTypes/Coroutine.cs:179)
LuaContext:ResumeAwaitedScript () (at Assets/Scripts/Lua/LuaContext.cs:149)
LuaContext/<RunRoutineFromLuaInternal>d__17:MoveNext () (at Assets/Scripts/Lua/LuaContext.cs:87)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:118)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<object>:Complete (object,System.Exception) (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:170)
IEnumeratorAwaitExtensions/CoroutineWrapper`1/<Run>d__3<object>:MoveNext () (at Assets/Plugins/AsyncAwaitUtil/Source/IEnumeratorAwaitExtensions.cs:284)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by psywombats** [comment]
didn't commit the BGM index

**Comment by psywombats** [comment]
Forgot to disable level ups here -- have done so now
