### ISSUE TITLE
Varonis preliminary issues

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#824]
1. This area in the NW corner where the wall suddenly ends:

![Screenshot 2023-01-08 15 58 23](https://user-images.githubusercontent.com/60168946/211225808-45cbd0a5-544a-4859-a1e3-56d74b4cb333.png)

I figure this is probably intended, since a similar exit that allows you to wind up on the north side of the city exists in the ruined version. But, it is a little weird because it implies that the city is built on a slope, while the world map shows the area as being a flat surface.

2. You can go out of bounds right here:

![Screenshot 2023-01-08 15 59 13](https://user-images.githubusercontent.com/60168946/211225866-c9326716-10f9-4ccb-aafa-a1e55ea9e3ff.png)
![Screenshot 2023-01-08 15 59 15](https://user-images.githubusercontent.com/60168946/211225869-d00bf72a-d9f4-44b2-bf3a-8ba16474a9b0.png)

The same is possible on the opposite side, as well:

![Screenshot 2023-01-08 15 59 26](https://user-images.githubusercontent.com/60168946/211225881-13c8ab93-cc01-478b-b0d4-d09518aa7e49.png)

3. Some weird pathing interactions in the front of the ruined city:

https://user-images.githubusercontent.com/60168946/211225927-3ebe43e2-d3db-4a15-bd99-8dc6330497d0.mp4

4. Leaving Babel into either version of the city teleports you to the west of the gate, rather than just outside the gate:

![Screenshot 2023-01-08 16 07 28](https://user-images.githubusercontent.com/60168946/211225959-6dacdf53-ba43-4749-b4f7-47ac0a6b3620.png)
![Screenshot 2023-01-08 16 08 31](https://user-images.githubusercontent.com/60168946/211225965-df17cecf-3e50-4570-9664-533f936de523.png)

**Comment by SkankinGarbage** [comment]
So far, I've checked the Rudra cutscenes, but now the cutscene from when you first come back to the Home World. The only thing is, the Masters BGM starts briefly right after the boss fight, before going to the right music.

**Comment by psywombats** [comment]
Thanks for the reports. This is one of the only locations still using manual teleport coordinates from the very early MotDW version.
